#!/usr/bin/env python3
"""Embed images/logo-mark.svg and images/pattern-cubes.png into css/theme.css as the data-URI variables --wm-mask and --cubes-mask
(between the MARK-MASK markers).

Why: the hero logo paints the G through a CSS mask, and the light sections tint the cubes pattern through one. Browsers fetch mask images with CORS, which fails when the site is
opened as a plain file (file://), so the G vanished. A data: URI always works. Re-run after changing images/logo-mark.svg or images/pattern-cubes.png.
"""
import base64, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
svg = (ROOT / "images" / "logo-mark.svg").read_bytes()
uri = "data:image/svg+xml;base64," + base64.b64encode(svg).decode()
cubes = "data:image/png;base64," + base64.b64encode((ROOT / "images" / "pattern-cubes.png").read_bytes()).decode()
css = ROOT / "css" / "theme.css"
text = css.read_text(encoding="utf-8")
block = f"/* MARK-MASK:start (generated by research/scripts/build-mask.py) */\n:root {{ --wm-mask: url(\"{uri}\"); --cubes-mask: url(\"{cubes}\"); }}\n/* MARK-MASK:end */"
if "MARK-MASK:start" in text:
    text = re.sub(r"/\* MARK-MASK:start.*?MARK-MASK:end \*/", lambda m: block, text, flags=re.S)
else:
    text = text.rstrip("\n") + "\n\n" + block + "\n"
css.write_text(text, encoding="utf-8")
print("wrote --wm-mask", len(uri), "and --cubes-mask", len(cubes), "bytes")
