"""Copy for the SEO pages (landing pages, guides, guides hub). Rendered by build-pages.py.

Rules kept from the brief: "we" voice, no pricing, no margin/transparency talk, no invented statistics
(the only numbers are Gratovo's own standards: 30K+ average views, 3-8% engagement, 35%+ audience in the
target country). Keyword plan lives in research/seo-research.md.

Block types (rendered by build-pages.py):
  ("h2", text)   ("h3", text)   ("p", html)   ("ul", [html, ...])   ("ol", [html, ...])
  ("note", html)                 a highlighted aside
Internal links are plain relative hrefs (flat site, every page at the root).
"""

DATE = "2026-10-08"

# icons must exist in fonts/material-symbols-subset.woff2
PAGES = [
    # ------------------------------------------------------------------ landing pages
    dict(
        slug="saas-influencer-marketing", kind="landing", aud="brand",
        title="SaaS Influencer Marketing: Vetted Creators for Your Product | Gratovo",
        desc="SaaS influencer marketing without the busywork. We find and vet creators for your AI or SaaS product, recommend one to three, and make the introduction.",
        crumb="SaaS influencer marketing",
        eyebrow="SaaS influencer marketing",
        h1="SaaS Influencer Marketing, Without the Busywork.",
        lead="We connect AI and SaaS brands with vetted creators who show your product to people who need it. You get one to three recommended creators, a proper introduction, and the last word on the video.",
        cta="Find My Creators", cta_href="#workwithus",
        cards=[
            ("smart_display", "Show, Don't Tell", "A creator walks through your product on screen. Viewers see it working before they ever sign up."),
            ("verified", "Vetted Before You See a Name", "We check real average views, engagement and audience location first, so the list is short on purpose."),
            ("handshake", "We Make the Introduction", "Introduction, contract, script and posting date are taken care of. You approve the video before it goes live."),
        ],
        stats=True,
        blocks=[
            ("h2", "Why creators work for SaaS"),
            ("p", "Software is easier to understand when you watch someone use it. A creator who builds something with your tool, or compares it with the one their audience uses today, answers the question every buyer has: what does this actually do for me?"),
            ("p", "That is why SaaS influencer marketing leans on tutorials, walkthroughs and honest comparisons rather than slogans. The audience already trusts the creator, and the product gets explained in a voice they know."),
            ("h2", "What a good fit looks like"),
            ("ul", [
                "AI and SaaS products that people can try: tools, apps and platforms.",
                "A product that is easy to show in a tutorial or a walkthrough.",
                "A clear audience: you know who uses it and what problem it solves.",
            ]),
            ("p", "Not sure whether your product suits creator content? Send us a short message about what you sell and who it is for. We reply within 24 hours."),
            ("h2", "How it works"),
            ("ol", [
                "<strong>Tell us what you sell.</strong> A short message about your product and who it is for.",
                "<strong>Creator matching.</strong> You get 1 to 3 vetted creators with their views and audience details, never a list of 200.",
                "<strong>Introduction and deal.</strong> We introduce you and keep the conversation moving until you both agree.",
                "<strong>Review and go live.</strong> We coordinate the contract, script and posting date. You approve the video before it posts.",
                "<strong>Reporting and scaling.</strong> We track how each video performs, then help you scale with the creators who deliver.",
            ]),
            ("h2", "Learn more"),
            ("ul", [
                '<a href="ai-influencer-marketing-guide.html">AI influencer marketing: a practical guide</a>',
                '<a href="how-to-vet-ai-creators-before-sponsoring.html">How to vet an AI creator before you sponsor them</a>',
                '<a href="ai-youtube-sponsorships.html">AI YouTube sponsorships</a>',
            ]),
        ],
        faq=[
            ("What is SaaS influencer marketing?",
             "It means working with creators who show your software to an audience that already trusts them, usually through tutorials, walkthroughs, comparisons or newsletter and social posts."),
            ("Does influencer marketing work for B2B software?",
             "It can, when the creator's audience is the people who use or buy that kind of tool. That is why we check audience location and engagement, not just follower counts."),
            ("How many creators will you recommend?",
             "One to three for your product, not a list of 200. A short list is easier to compare and easier to repeat with."),
            ("What kinds of products do you work with?",
             "AI and SaaS products that people can try: tools, apps and platforms that are easy to show in a tutorial or a walkthrough."),
            ("How long until a video goes live?",
             "We reply within 24 hours. Most deals go live within about a month."),
        ],
        related=["ai-influencer-marketing-guide", "how-to-vet-ai-creators-before-sponsoring", "ai-youtube-sponsorships"],
    ),
    dict(
        slug="ai-youtube-sponsorships", kind="landing", aud="brand",
        title="AI YouTube Sponsorships: Sponsor the Creators Buyers Watch | Gratovo",
        desc="Sponsor AI YouTubers your buyers already trust. We find and vet the creators, make the introduction, and you approve the video before it goes live.",
        crumb="AI YouTube sponsorships",
        eyebrow="AI YouTube sponsorships",
        h1="Sponsor the AI YouTubers Your Buyers Already Watch.",
        lead="We find the creators whose audience fits your product, check their real numbers, and introduce you. One to three recommended creators, one clear deal, and you approve the video before it posts.",
        cta="Find My Creators", cta_href="#workwithus",
        cards=[
            ("search", "We Do the Searching", "No hours on YouTube, no cold emails, no waiting on replies. You only hear about the creators worth your time."),
            ("groups", "A Short, Vetted List", "Real average views, engagement and audience location are checked before you see a name."),
            ("visibility", "You Approve the Video", "We coordinate the contract, script and posting date. Nothing goes live without your yes."),
        ],
        stats=True,
        blocks=[
            ("h2", "How AI YouTube sponsorships work"),
            ("p", "A sponsorship is a paid partnership where a creator features your product in a video for their audience. On AI and software channels it usually takes one of three shapes:"),
            ("ul", [
                "<strong>Dedicated video:</strong> the whole video is about your product. The most room to demonstrate it, best for tools that need a walkthrough.",
                "<strong>Integration:</strong> a segment inside a video the creator was already making. It works when the product fits the topic naturally.",
                "<strong>Mention:</strong> a short, clearly labelled shout-out. It suits simple products that explain themselves quickly.",
            ]),
            ("p", "The more steps a viewer needs to understand your product, the more room the creator needs. We help you choose the format when we scope the deal."),
            ("h2", "Why YouTube suits AI tools"),
            ("p", "People look for AI and software tools by watching how they work. A tutorial answers 'is this for me?' faster than a landing page, and a good one keeps being found long after the posting date."),
            ("h2", "What we check before you see a name"),
            ("p", "Subscriber count tells you who a creator was. Recent reach tells you what a sponsorship will actually get. So we look at average views per video, real engagement from active viewers, and where the audience lives. Our standards are on this page, and the full checklist is in our guide on <a href=\"how-to-vet-ai-creators-before-sponsoring.html\">vetting an AI creator</a>."),
            ("h2", "After the video goes live"),
            ("p", "We track how each video performs. When one works, we help you scale with the creators who deliver, rather than starting from zero each time."),
            ("h2", "Keep reading"),
            ("ul", [
                '<a href="how-to-find-ai-youtubers-to-sponsor.html">How to find AI YouTubers to sponsor</a>',
                '<a href="ai-influencer-marketing-guide.html">AI influencer marketing: a practical guide</a>',
                '<a href="saas-influencer-marketing.html">SaaS influencer marketing</a>',
            ]),
        ],
        faq=[
            ("What is the difference between a dedicated video and an integration?",
             "A dedicated video is entirely about your product. An integration is a segment inside a video on a wider topic. Dedicated videos give more room to demonstrate; integrations suit products that fit the topic naturally."),
            ("Do I get to approve the video?",
             "Yes. You approve the video before it goes live."),
            ("How long until a sponsored video goes live?",
             "We reply within 24 hours. Most deals go live within about a month."),
            ("Do you only work with YouTube?",
             "No. We work with creators on YouTube, LinkedIn, X and newsletters. YouTube is the most common starting point for software products."),
            ("How do you report results?",
             "We track how each video performs. When one works, we help you scale with the creators who deliver."),
        ],
        related=["how-to-find-ai-youtubers-to-sponsor", "how-to-vet-ai-creators-before-sponsoring", "ai-influencer-marketing-guide"],
    ),
    dict(
        slug="ai-youtuber-brand-deals", kind="landing", aud="creator",
        title="Brand Deals for AI YouTubers and Tech Creators | Gratovo",
        desc="Make content about AI and software? We put you in front of AI and SaaS brands that fit your audience. One contact, no cold outreach, and you decide.",
        crumb="Brand deals for AI YouTubers",
        eyebrow="Brand deals for creators",
        h1="Brand Deals for AI YouTubers and Tech Creators.",
        lead="Already making content about AI and software? We put you in front of the AI and SaaS brands that fit your audience, so the deals come to you instead of you pitching cold.",
        cta="Get Brand Deals", cta_href="#creators",
        cards=[
            ("handshake", "Brand Deals Come to You", "No cold outreach to brands. We bring AI and SaaS sponsorship deals to creators who fit."),
            ("person", "One Contact, Less Back-and-Forth", "No long media-kit requests or endless email threads. One person to talk to."),
            ("trending_up", "Repeat Deals", "We track how your video performs, then line up the next brand that fits."),
        ],
        stats=False,
        blocks=[
            ("h2", "Who we work with"),
            ("p", "Creators making content about AI and software, on YouTube, LinkedIn, X or newsletters. We look at average views, engagement and where your audience is. Send your channel link and we will tell you if there is a fit."),
            ("h2", "How it works for creators"),
            ("ol", [
                "<strong>Tell us about your channel.</strong> Your channel link and what you cover. It takes two minutes.",
                "<strong>Brand matching.</strong> We match you with AI and SaaS brands that fit your audience.",
                "<strong>A deal that fits.</strong> When a brand fits, we bring you the details. You decide.",
                "<strong>Create and go live.</strong> You make the video. We keep the brand conversation moving until it posts.",
                "<strong>Reporting and repeat deals.</strong> We track how your video performs, then line up the next brand that fits.",
            ]),
            ("h2", "What brands look for"),
            ("p", "Brands in this space want creators whose recent videos reliably reach people who use software, whose audience is in the right country, and whose comments show real interest. Our own standards are 30K+ average views per video, 3-8% engagement from active viewers and 35%+ of the audience in the brand's target country."),
            ("h2", "Learn more"),
            ("ul", [
                '<a href="how-ai-creators-get-brand-sponsorships.html">How AI and tech creators get brand sponsorships</a>',
                '<a href="ai-influencer-marketing-guide.html">AI influencer marketing: a practical guide</a>',
            ]),
        ],
        faq=[
            ("How does Gratovo find me brand deals?",
             "You tell us about your channel. We put you forward to AI and SaaS brands that fit your audience, so the deals come to you instead of you pitching cold."),
            ("What kind of channel do you work with?",
             "Creators making content about AI and software, on YouTube, LinkedIn, X or newsletters. We look at average views, engagement and where your audience is, so send your link and we will tell you if there is a fit."),
            ("Do I choose which brands I work with?",
             "Yes. When a brand fits, we bring you the details and you decide."),
            ("Who will I be talking to?",
             "One contact at Gratovo. No long media-kit requests and no endless email threads."),
            ("How quickly will I hear back?",
             "We reply within 24 hours."),
        ],
        related=["how-ai-creators-get-brand-sponsorships", "ai-influencer-marketing-guide"],
    ),

    # ------------------------------------------------------------------ guides
    dict(
        slug="ai-influencer-marketing-guide", kind="article", aud="brand",
        title="AI Influencer Marketing: A Practical Guide for AI and SaaS Brands",
        desc="What AI influencer marketing is, why it suits AI and SaaS products, and how to choose creators, brief them, approve videos and measure results.",
        crumb="AI influencer marketing guide",
        h1="AI Influencer Marketing: A Practical Guide for AI and SaaS Brands",
        lead="What it is, why it works for software, and how to run it without wasting a month on outreach.",
        takeaways=[
            "Here, AI influencer marketing means working with real creators to show your AI or SaaS product to their audience. It is not about AI-generated avatars.",
            "It works best for products that are easy to demonstrate: a tutorial or walkthrough does the selling.",
            "Choose creators by average views, engagement quality and audience location, not follower count.",
            "Give the creator one clear angle and one call to action, then approve the video before it goes live.",
            "Track each creator with their own link, and repeat with the ones who deliver.",
        ],
        blocks=[
            ("h2", "What AI influencer marketing means"),
            ("p", "The phrase gets used for two different things. Some people mean virtual, AI-generated personalities. We mean something simpler: AI and SaaS brands working with real creators on YouTube, LinkedIn, X and newsletters, who show the product to an audience that already trusts them."),
            ("p", "A creator who builds something with your tool on screen, or compares it with the tool their audience uses today, does what an ad cannot: it shows the product working, in a voice the viewer already knows."),
            ("h2", "Why it suits AI and SaaS products"),
            ("ul", [
                "<strong>Software can be shown.</strong> A tutorial or walkthrough is the natural format, so viewers see the result before they sign up.",
                "<strong>Buyers research before they try.</strong> People looking for new tools often watch videos and read newsletters from practitioners they follow.",
                "<strong>Trust travels.</strong> A recommendation from someone the viewer already follows carries context a banner ad lacks.",
                "<strong>Videos keep working.</strong> A good tutorial can keep collecting views long after the posting date.",
            ]),
            ("h2", "Choose the format"),
            ("ul", [
                "<strong>Dedicated video:</strong> the whole video is about your product. The most room to explain, best for tools that need a demo.",
                "<strong>Integration:</strong> a segment inside a video the creator was already making. It works when the product fits the topic naturally.",
                "<strong>Newsletter, LinkedIn or X post:</strong> a shorter format that reaches people where they read about tools.",
            ]),
            ("p", "The more steps a viewer needs to understand your product, the more room the creator needs. Start from how hard the product is to explain."),
            ("h2", "Pick the right creators"),
            ("p", "Subscriber count is the easiest number to see and one of the least useful. What matters is what the creator's recent videos actually reach. Before a creator makes our shortlist we check three things:"),
            ("ul", [
                "<strong>30K+ average views per video</strong>, measured on recent uploads.",
                "<strong>3-8% engagement</strong> from active viewers, with real questions and comments rather than generic praise.",
                "<strong>35%+ of the audience in your target country</strong>, confirmed from analytics rather than a screenshot of one good video.",
            ]),
            ("p", 'The full method is in <a href="how-to-vet-ai-creators-before-sponsoring.html">how to vet an AI creator before you sponsor them</a>. Also watch their earlier sponsored videos: do they really use the product, and does the audience respond?'),
            ("h2", "Write a brief that helps the creator"),
            ("ul", [
                "What the product does, in two sentences.",
                "Who it is for and the one problem it solves.",
                "The one thing you want the viewer to do. One link, not five.",
                "Anything that must be said, and anything that must not.",
                "Access to the product, so the creator can use it before filming.",
            ]),
            ("p", "Leave room for the creator's voice. Their audience follows them for how they explain things, and a script that reads like an advert usually lands worse than a real walkthrough."),
            ("h2", "Approvals, disclosure and contracts"),
            ("p", "Agree the deliverable, the posting date and the approval step in writing before filming starts. You should approve the video before it goes live. Paid partnerships must be disclosed clearly: use the platform's paid-promotion label and follow the advertising rules where your audience lives. This is general guidance, not legal advice."),
            ("h2", "Measure what happened"),
            ("ul", [
                "Give each creator their own link, so you can see the clicks and sign-ups they send.",
                "Look at views, watch behaviour and comments as well as clicks. Tutorial viewers often come back later.",
                "Compare creators with each other, then repeat with the ones who deliver.",
            ]),
            ("h2", "Common mistakes"),
            ("ul", [
                "Choosing by subscriber count.",
                "Contacting fifty creators at once and running fifty conversations.",
                "Over-scripting the video.",
                "Asking for several calls to action.",
                "Judging the result too early.",
            ]),
            ("h2", "Where Gratovo fits"),
            ("p", 'Gratovo is a broker. You tell us what you sell. We find and check the creators, recommend one to three, make the introduction and keep the conversation moving until you both agree. We also take care of the contract, script and posting date, and you approve the video before it goes live. See <a href="brands.html">how it works for brands</a>, or <a href="creators.html">how it works for creators</a>.'),
        ],
        faq=[
            ("What is AI influencer marketing?",
             "Working with real creators to show your AI or SaaS product to an audience that already trusts them, usually through tutorials, walkthroughs, comparisons or newsletter and social posts."),
            ("Is it about AI-generated influencers?",
             "No. This guide is about promoting AI and software products through real creators. Virtual, AI-generated personalities are a different topic."),
            ("Which platforms work for AI and SaaS products?",
             "YouTube is the most common starting point because tutorials and walkthroughs suit software. LinkedIn, X and newsletters also reach people who follow tools and workflows."),
            ("How many creators should a brand start with?",
             "A short list. We recommend one to three for each product, so you can compare results and repeat with the best."),
            ("How long does it take?",
             "We reply within 24 hours. Most deals go live within about a month."),
        ],
        related=["how-to-find-ai-youtubers-to-sponsor", "how-to-vet-ai-creators-before-sponsoring", "ai-youtube-sponsorships"],
    ),
    dict(
        slug="how-to-find-ai-youtubers-to-sponsor", kind="article", aud="brand",
        title="How to Find AI YouTubers to Sponsor (and Which Are Worth It)",
        desc="How to find AI YouTubers to sponsor: search like your buyer, shortlist ten, cut to three, check fit and write a first message that gets answered.",
        crumb="Find AI YouTubers to sponsor",
        h1="How to Find AI YouTubers to Sponsor (and Which Ones Are Worth It)",
        lead="Search like your buyer, shortlist ten, cut to three, and send a message worth answering.",
        takeaways=[
            "Start from your buyer's problem, not from a list of famous channels.",
            "Search YouTube the way your buyer does, and note who keeps showing up.",
            "Shortlist about ten channels, then cut to three after checking real numbers and fit.",
            "Read earlier sponsored videos to see how a creator treats a product.",
            "Keep the first message short and specific, or hand the whole search to a broker.",
        ],
        blocks=[
            ("h2", "Start with the viewer, not the creator"),
            ("p", "Write down who uses your product, what job it does, and what they type into YouTube when they look for help. A product that automates support tickets is searched for differently from one that helps developers write tests."),
            ("h2", "Search the way your buyer searches"),
            ("ul", [
                "Search for the problem you solve, in the words a customer would use.",
                "Search for 'best AI tools for' plus the job your product does.",
                "Search for tutorials of tools similar to yours and tools next to yours.",
                "Note which channels appear again and again, and which have recent uploads.",
            ]),
            ("p", "Open a channel's Videos tab and sort by popular, then by latest. If one video has ten times the views of the rest, that is a one-off hit, not what a sponsorship will typically reach."),
            ("h2", "Look at who already covers your category"),
            ("p", "Videos that carry a paid-promotion label or a sponsor segment show which creators accept sponsorships and how they present them. Watch a few. A good integration explains the product in the creator's own words and shows it working."),
            ("h2", "Shortlist ten, then cut to three"),
            ("p", 'For each channel, check average views on recent uploads, the quality of the comments, and where the audience lives. The method is in <a href="how-to-vet-ai-creators-before-sponsoring.html">how to vet an AI creator before you sponsor them</a>. A short final list is easier to compare, and easier to repeat with.'),
            ("h2", "Check fit before you write"),
            ("ul", [
                "<strong>Topic:</strong> does the creator already cover this kind of problem?",
                "<strong>Level:</strong> does the audience skew beginner, practitioner or developer, and is that your buyer?",
                "<strong>Quality:</strong> are the last few videos well made and consistent?",
                "<strong>Conflicts:</strong> have they recently promoted a direct competitor?",
            ]),
            ("h2", "Make the first message short and specific"),
            ("p", "Most creators list a business contact in the About tab of the channel. A message that gets answered usually has five parts: who you are, what the product does in one line, why you picked this creator, what you propose, and how to reply. Skip the long deck. Mention a video you actually watched."),
            ("h2", "What the search really costs"),
            ("p", 'Searching, checking each channel, writing to ten creators and chasing replies takes days of attention. That is the work a broker takes over. At Gratovo we do the search and the checks, recommend one to three creators, and make the introduction. See <a href="ai-youtube-sponsorships.html">AI YouTube sponsorships</a> or <a href="brands.html">how it works for brands</a>.'),
        ],
        faq=[
            ("Where do I find an AI YouTuber's business contact?",
             "Most creators list a business email in the About tab of their channel. Some prefer a contact form or work through an agent."),
            ("Should I sponsor big channels or small ones?",
             "Judge by average views and audience fit rather than size. A smaller channel with an audience that matches your buyer can beat a bigger one with the wrong audience."),
            ("How many creators should I contact?",
             "A short list of three after checking. Contacting dozens creates dozens of conversations to manage."),
            ("Can someone else do this for me?",
             "Yes. We find and check the creators, recommend one to three, and make the introduction."),
        ],
        related=["how-to-vet-ai-creators-before-sponsoring", "ai-youtube-sponsorships", "ai-influencer-marketing-guide"],
    ),
    dict(
        slug="how-to-vet-ai-creators-before-sponsoring", kind="article", aud="brand",
        title="How to Vet an AI Creator Before You Sponsor Them (Checklist)",
        desc="Vet an AI or tech creator before you sponsor: average views, engagement quality, audience location, consistency, past sponsors and red flags.",
        crumb="Vet an AI creator",
        h1="How to Vet an AI Creator Before You Sponsor Them",
        lead="Six checks and a short list of red flags, in the order we run them.",
        takeaways=[
            "Average views on recent videos tell you more than subscriber count.",
            "Read the comments: real questions about tools beat generic praise.",
            "Ask for audience analytics and check the creator's location claim against them.",
            "Look for steady growth, and ask about sudden jumps.",
            "Our standards: 30K+ average views, 3-8% engagement from active viewers, 35%+ of the audience in your target country.",
        ],
        blocks=[
            ("h2", "1. Look at average views, not subscribers"),
            ("p", "Subscribers show how many people clicked once. Recent views show who still watches. Open the last ten to twenty long-form uploads, ignore the single biggest hit, and take the typical number. That is closest to what a sponsored video can reach. Our standard is 30K+ average views per video."),
            ("h2", "2. Judge engagement by quality as well as rate"),
            ("p", "A simple engagement rate is likes plus comments divided by views. We look for 3-8% from active viewers. The number only helps if it is real, so read the comments. Questions about the tools in the video, people sharing what they tried, and follow-up requests are good signs. Repetitive, generic or off-topic comments are not."),
            ("h2", "3. Confirm where the audience is"),
            ("p", "If your product serves one country or language, audience location matters more than size. Ask the creator for a screenshot of the audience geography from their analytics (YouTube Studio shows this) for the last 28 to 90 days, and compare it with what they claimed. We look for 35%+ of the audience in your target country. A creator who shares analytics easily is usually a good sign."),
            ("h2", "4. Check consistency over time"),
            ("ul", [
                "Do they upload on a steady rhythm?",
                "Do views stay in a similar range from video to video?",
                "Is there a sudden jump in subscribers or views with no clear reason? Ask about it.",
            ]),
            ("h2", "5. Read earlier sponsored videos"),
            ("p", "Find videos with a paid-promotion label or a sponsor segment. Does the creator show the product working? Do viewers react in the comments? Have they promoted a direct competitor recently? Past integrations are the best preview of yours."),
            ("h2", "6. Check topic and brand fit"),
            ("p", "A creator can have excellent numbers and still be wrong for your product. Check that they already cover the problem you solve, at a level your buyer is at, in a tone that suits your brand."),
            ("h2", "Red flags"),
            ("ul", [
                "Subscribers jump by thousands with no matching change in views.",
                "Engagement is almost identical on every video, whatever the topic.",
                "Comments are generic, repetitive or full of unrelated accounts.",
                "The audience location they claim does not match their analytics.",
                "Unwilling to share any analytics at all.",
            ]),
            ("h2", "One-page checklist"),
            ("ol", [
                "Average views on the last 10 to 20 long-form videos.",
                "Engagement rate and comment quality.",
                "Audience location from analytics.",
                "Upload rhythm and growth pattern.",
                "Two or three earlier sponsored videos.",
                "Topic, level and tone fit.",
            ]),
            ("h2", "What we do at Gratovo"),
            ("p", 'We run these checks before you see a name, so the list is short on purpose: one to three creators, with their views and audience details. See <a href="brands.html">how it works for brands</a>, or read the <a href="ai-influencer-marketing-guide.html">full guide to AI influencer marketing</a>.'),
        ],
        faq=[
            ("What is a good engagement rate on YouTube?",
             "It depends on the niche and the size of the channel. For AI and software content we look for 3-8% from active viewers, and we read the comments to make sure the engagement is real."),
            ("Can I check audience location from a public page?",
             "Not reliably. Ask the creator for a screenshot of the audience geography from their analytics, or work with someone who checks it for you."),
            ("Are subscriber counts useless?",
             "No, but they show history rather than current reach. Average views on recent videos are a better guide to what a sponsorship will deliver."),
            ("How many videos should I look at?",
             "The last ten to twenty long-form uploads, ignoring the single biggest hit."),
        ],
        related=["how-to-find-ai-youtubers-to-sponsor", "ai-influencer-marketing-guide", "saas-influencer-marketing"],
    ),
    dict(
        slug="how-ai-creators-get-brand-sponsorships", kind="article", aud="creator",
        title="How AI and Tech Creators Get Brand Sponsorships",
        desc="What brands check before sponsoring an AI or tech creator, what to put in a one-page overview, where deals come from and how to turn one deal into repeat deals.",
        crumb="How creators get sponsored",
        h1="How AI and Tech Creators Get Brand Sponsorships",
        lead="What brands look at, what to send them, and how to turn one deal into the next.",
        takeaways=[
            "Brands look at average views, audience fit and consistency before they look at subscribers.",
            "A one-page overview is enough: channel link, topics, average views, audience location and your best videos.",
            "Deals come from inbound brands, your own outreach, platforms and brokers.",
            "Only take deals for products you would use and your audience needs.",
            "Be easy to work with, share results, and repeat deals follow.",
        ],
        blocks=[
            ("h2", "What brands look at first"),
            ("ul", [
                "<strong>Average views</strong> on recent videos, not just subscribers.",
                "<strong>Audience fit:</strong> do the people watching use this kind of product, and are they in the right country?",
                "<strong>Consistency:</strong> steady uploads and steady views.",
                "<strong>Quality of earlier integrations:</strong> did past sponsored videos feel natural?",
                "<strong>Professionalism:</strong> clear communication and on-time delivery.",
            ]),
            ("h2", "Make a one-page overview"),
            ("p", "Long media kits slow everything down. One page is enough:"),
            ("ul", [
                "Your channel link and what you cover.",
                "Average views on your recent videos.",
                "Where your audience lives, from your analytics.",
                "Two or three of your best videos.",
                "Examples of earlier sponsored videos, if you have them.",
                "The best email to reach you.",
            ]),
            ("h2", "Where deals come from"),
            ("ul", [
                "<strong>Inbound:</strong> brands find you and write to you.",
                "<strong>Your own outreach:</strong> you pitch brands you already use.",
                "<strong>Platforms:</strong> for example, YouTube's own creator partnership tools.",
                "<strong>Brokers:</strong> someone who brings matching deals to you and keeps the conversation moving.",
            ]),
            ("p", "Cold outreach works, but it costs time and many messages go unanswered. A broker moves that work off your plate."),
            ("h2", "Judge whether a deal fits"),
            ("ul", [
                "Would you use the product yourself?",
                "Does your audience have the problem it solves?",
                "Is the deliverable, posting date and approval step agreed in writing?",
                "Is the paid partnership disclosed clearly, using the platform's label?",
            ]),
            ("p", "You do not have to accept every offer. A deal that does not fit costs you audience trust."),
            ("h2", "Be easy to work with"),
            ("p", "Reply quickly, deliver drafts on the agreed date, and ask questions early. Brands remember creators who make the process smooth."),
            ("h2", "Turn one deal into repeat deals"),
            ("p", "When the video is live, look at how it performed and share the highlights. Brands that see results come back, and brokers line up the next fitting brand sooner."),
            ("h2", "How Gratovo works with creators"),
            ("p", 'You send us your channel link and what you cover. We match you with AI and SaaS brands that fit your audience, bring you the details when one fits, and you decide. One contact, no long media-kit requests. See <a href="creators.html">how it works for creators</a> or <a href="ai-youtuber-brand-deals.html">brand deals for AI YouTubers</a>.'),
        ],
        faq=[
            ("Do I need a minimum number of subscribers?",
             "There is no universal number. Brands look at average views and audience fit. At Gratovo we look for 30K+ average views per video, 3-8% engagement and 35%+ of the audience in the brand's target country."),
            ("Do I have to accept every deal?",
             "No. When a brand fits we bring you the details and you decide."),
            ("Which platforms do you work with?",
             "YouTube, LinkedIn, X and newsletters."),
            ("How quickly will I hear back?",
             "We reply within 24 hours."),
        ],
        related=["ai-youtuber-brand-deals", "ai-influencer-marketing-guide"],
    ),
]

HUB = dict(
    slug="guides", crumb="Guides",
    title="Influencer Marketing Guides for AI and SaaS | Gratovo",
    desc="Practical guides on AI influencer marketing: how to find and vet AI creators for sponsorships, and how AI and tech creators get brand deals.",
    h1="Guides for AI and SaaS Brands and Creators",
    lead="Practical, no-fluff guides on working with creators in the AI and software space.",
)
